# Site settings
title: Becoming a full stack developer in 6 months
email: charlie.coggans@mayden.co.uk
description: A blog about learning software engineering in a hurry
baseurl: '/mayden_blog'
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: MaydenAcademy
github_username:  charliecog

# Build settings
markdown: kramdown
permalink: /:title
